name: Stock Market Trading Bot

on:
  schedule:
    # Each line represents a different hour during market hours (IST 9:15 AM - 3:30 PM)
    - cron: '*/5 3 * * 1-5'  # 8:30-9:00 IST
    - cron: '*/5 4 * * 1-5'  # 9:30-10:00 IST
    - cron: '*/5 5 * * 1-5'  # 10:30-11:00 IST
    - cron: '*/5 6 * * 1-5'  # 11:30-12:00 IST
    - cron: '*/5 7 * * 1-5'  # 12:30-13:00 IST
    - cron: '*/5 8 * * 1-5'  # 13:30-14:00 IST
    - cron: '*/5 9 * * 1-5'  # 14:30-15:00 IST
    - cron: '*/5 10 * * 1-5' # 15:30-16:00 IST
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  run-stock-bot:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance==0.2.36
        pip install pandas==2.1.4 
        pip install numpy==1.26.2
        pip install python-telegram-bot==20.7
        pip install pytz==2023.3.post1
        pip install python-dotenv
        
    - name: Run Stock Market Bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python stock_screener.py