name: Stock Market Trading Bot

on:
  schedule:
    # Runs every 5 minutes during Indian market hours (9:15 AM - 3:30 PM IST)
    # Format: minute hour * * day(1-5 for Mon-Fri)
    - cron: '*/5 3:45-10:00 * * 1-5'  # UTC timing for IST market hours
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

permissions: # Add explicit permissions
  contents: read
  actions: write

jobs:
  run-stock-bot:
    runs-on: ubuntu-latest
    concurrency: # Add concurrency to prevent overlapping runs
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance==0.2.36
        pip install pandas==2.1.4 
        pip install numpy==1.26.2
        pip install python-telegram-bot==20.7
        pip install pytz==2023.3.post1
        pip install python-dotenv
        
    - name: Run Stock Market Bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python stock_screener.py