name: Stock Market Trading Bot

on:
  schedule:
    # Every 5 minutes during market hours (Indian Standard Time)
    - cron: '*/5 4-9 * * 1-5'  # UTC equivalent of 9:15 AM to 3:30 PM IST
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

jobs:
  run-stock-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy python-telegram-bot pytz
    
    - name: Run Stock Market Bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python stock_screener.py