name: Stock Market Trading Bot

on:
  schedule:
    # Runs every 5 minutes during Indian market hours (9:15 AM - 3:30 PM IST)
    - cron: '*/5 3:45-10:00 * * 1-5'  # UTC timing adjusted for IST market hours
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

jobs:
  run-stock-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install additional dependencies
      run: |
        pip install yfinance==0.2.36
        pip install pandas numpy python-telegram-bot==13.7 python-dotenv pytz
    
    - name: Run Stock Market Bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python stock_screener.py